/*
 * JSelectPersonByRoleDialog.java
 *
 * Created on 22 maj 2008, 13:14
 */

package schoolmanagement.dialogs;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import schoolmanagement.controller.DBAccess;
import schoolmanagement.entity.SmPerson;
import schoolmanagement.entity.SmRole;

/**
 *
 * @author  deely
 */
public class JSelectPersonByRoleDialog extends javax.swing.JDialog {
    
    private SmRole m_role;
    private SmPerson m_result;
    
    /** Creates new form JSelectPersonByRoleDialog */
    public JSelectPersonByRoleDialog(java.awt.Frame parent, boolean modal, SmRole role ) {
        super(parent, modal);
        initComponents();
        
        m_role = role;
        m_result = null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTbName2 = new javax.swing.JTextField();
        jBtnSearch2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jbtSelect = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Wybierz osobe")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jTbName2.setName("jTbName2"); // NOI18N
        jTbName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTbName2FocusGained(evt);
            }
        });

        jBtnSearch2.setText("Szukaj"); // NOI18N
        jBtnSearch2.setName("jBtnSearch2"); // NOI18N
        jBtnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearch2ActionPerformed(evt);
            }
        });

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwisko i Imię", "Grupa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable6.setName("jTable6"); // NOI18N
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6mouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable6);

        jbtSelect.setText("Wybierz"); // NOI18N
        jbtSelect.setName("jbtSelect"); // NOI18N
        jbtSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSelectActionPerformed(evt);
            }
        });

        jbtCancel.setText("Anuluj"); // NOI18N
        jbtCancel.setName("jbtCancel"); // NOI18N
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTbName2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSearch2)
                    .addComponent(jTbName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSelect)
                    .addComponent(jbtCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTbName2FocusGained
        jRbSurname.setSelected(true);
    }//GEN-LAST:event_jTbName2FocusGained

    private void jBtnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearch2ActionPerformed
        // TODO add your handling code here:
        
        jRbSurname.setSelected(true);
        
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
        },
                new String [] {
            "Nazwisko i Imię", "Grupa"
        }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        
        List<SmPerson> list = new ArrayList<SmPerson>();
        list = DBAccess.GetInstance().GetUserByName(jTbName.getText().trim());
        
        for(SmPerson person : list){
            if( DBAccess.GetInstance().getUserByPerson(person).getUsrRolId() != m_role ) continue;
            model.addRow(new Object[]{person,
            person.getSmUserCollection().iterator().next().getUsrRolId().getRolName()});
            //int row = list.indexOf(person);
            //jTable4.setValueAt(person.getPerSurname(), row, 0);
            //jTable4.setValueAt(person.getPerName(), row, 1);
            //jTable4.setValueAt(person.getSmUserCollection().iterator().next().getUsrRolId().getRolName(), row, 2);
        }
    }//GEN-LAST:event_jBtnSearch2ActionPerformed

    private void jTable6mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6mouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            JTable target = (JTable)evt.getSource();
            int row = target.getSelectedRow();
            Object o = target.getValueAt(row, 0);
            if(o == null)
                return;
            SmPerson person = (SmPerson)target.getValueAt(row, 0);
            m_result = person;
            setVisible(false);
        }
    }//GEN-LAST:event_jTable6mouseClicked

    public SmPerson getResult()
    {
        return m_result;
    }
    
    private void jbtSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSelectActionPerformed
        
        if( jTable4.getSelectedRowCount() != 1 ) return;
        int row = jTable4.getSelectedRow();
        Object o = jTable4.getValueAt(row, 0);
        if(o == null) return;
        SmPerson person = (SmPerson)jTable4.getValueAt(row, 0);
        m_result = person;
        setVisible(false);
    }//GEN-LAST:event_jbtSelectActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        m_result = null;
        setVisible(false);
    }//GEN-LAST:event_jbtCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JSelectPersonByRoleDialog dialog = new JSelectPersonByRoleDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnSearch1;
    private javax.swing.JButton jBtnSearch2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRbSurname;
    private javax.swing.JRadioButton jRbSurname1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTbName;
    private javax.swing.JTextField jTbName1;
    private javax.swing.JTextField jTbName2;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtSelect;
    // End of variables declaration//GEN-END:variables
    
}
